name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Install BATS
      run: npm install -g bats

    - name: Clone MySQL-server
      run:
        git clone https://github.com/mysql/mysql-server.git

    - name: Set symbolic link in MySQL-server
      run:
        ln -s LineairDB-storage-engine mysql-server/storage/lineairdb
    - name: Make build directory
      run:
        mkdir mysql-server/build
    - name: CMake, MySQL initialization and start server
      run:
        cd mysql-server/build;
        cmake .. -DWITH_DEBUG=ON -DDOWNLOAD_BOOST=ON -DWITH_BOOST=../boost;
        make -j 8 || make -j 6 || make -j 4 || make;
        bin/mysqld --defaults-file=../storage/lineairdb/.github/my.cnf;
        bats ../storage/lineairdb/tests/test.bats;
